version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - ls    
      - npm run build
      
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'